name: Waka Readme

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: QEXLAUWASD
          SHOW_TOTAL: true
          SHOW_LINES_OF_CODE: true
          SHOW_PROFILE: true
          SHOW_LOC_CHART: false
